{{- $files := include "opencloud.configFiles" . | fromYamlArray }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.fullname" . }}-files
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  csp.yaml: |
    {{- .Values.csp.override | default (include "opencloud.csp" .) | nindent 4 }}
  {{- if has "proxy.yaml" $files }}
  proxy.yaml: |
    {{- include "opencloud.proxyConfig" . | nindent 4 }}
  {{- end }}
  {{- if has "banned-password-list.txt" $files }}
  banned-password-list.txt: |
    {{- join "\n" .Values.passwordPolicy.bannedPasswords | nindent 4 }}
  {{- end }}
  {{- if has "app-registry.yaml" $files }}
  app-registry.yaml: |
    {{- .Values.collaboration.appRegistry | nindent 4 }}
  {{- end }}
  {{- if has "apps.yaml" $files }}
  apps.yaml: |
    {{- toYaml .Values.web.appsConfig | nindent 4 }}
  {{- end }}
