{{- if eq (include "opencloud.needsManagedSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if and (not .Values.admin.existingSecret) .Values.admin.password }}
  adminPassword: {{ .Values.admin.password | quote }}
  {{- end }}
  {{- if and (eq .Values.storage.driver "decomposeds3") (not .Values.storage.s3.existingSecret) .Values.storage.s3.accessKey .Values.storage.s3.secretKey }}
  s3AccessKey: {{ .Values.storage.s3.accessKey | quote }}
  s3SecretKey: {{ .Values.storage.s3.secretKey | quote }}
  {{- end }}
  {{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) .Values.smtp.password }}
  smtpPassword: {{ .Values.smtp.password | quote }}
  {{- end }}
  {{- if and (eq (include "opencloud.externalLdap" .) "true") (not .Values.identity.ldap.existingSecret) .Values.identity.ldap.bindPassword }}
  ldapBindPassword: {{ .Values.identity.ldap.bindPassword | quote }}
  {{- end }}
  {{- if and (not .Values.metrics.token.existingSecret) .Values.metrics.token.value }}
  metricsToken: {{ .Values.metrics.token.value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
