apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
  annotations:
    {{- include "opencloud.annotations" (dict "specific" dict "context" .) | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 9200
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
  annotations:
    {{- include "opencloud.annotations" (dict "specific" .Values.service.annotations "context" .) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opencloud.componentLabels" (dict "component" "metrics" "context" .) | nindent 4 }}
  annotations:
    {{- include "opencloud.annotations" (dict "specific" dict "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
  ports:
    - name: debug
      port: {{ include "opencloud.debugPort" . }}
      targetPort: debug
{{- end }}
